#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-Strptime
version:      1.0701
version_from: lib/DateTime/Format/Strptime.pm
installdirs:  site
requires:
    Params::Validate:              0.64
    DateTime:                      0.1402
    DateTime::Locale:              0.35
    DateTime::TimeZone:            0.25

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
