#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-Strptime
version:      1.05
version_from: lib/DateTime/Format/Strptime.pm
installdirs:  site
requires:
    DateTime::Locale:              0.02
    DateTime::TimeZone:            0.25
    DateTime:                      0.1402
    Params::Validate:              0.64

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
