---
abstract: 'Parse and format strp and strf time patterns'
author:
  - 'Dave Rolsky <autarch@urth.org>'
build_requires:
  Module::Build: 0
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DateTime-Format-Strptime
provides:
  DateTime::Format::Strptime:
    file: lib/DateTime/Format/Strptime.pm
    version: 1.2000
requires:
  DateTime: 0.4304
  DateTime::Locale: 0.45
  DateTime::TimeZone: 0.79
  Params::Validate: 0.64
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=DateTime-Format-Strptime
  homepage: http://datetime.perl.org/
  license: http://dev.perl.org/licenses/
  repository: http://hg.urth.org/hg/DateTime-Format-Strptime
version: 1.2000
