--- #YAML:1.0
meta-spec:
        version: 1.3
        url: http://module-build.sourceforge.net/META-spec-v1.3.html
name:           DateTime-Format-Strptime
version:        1.0702
abstract:       Parse and format strp and strf time patterns
author:
        - Rick Measham <rickm@cpan.org>
licence:        perl
distribution_type:      module
requires:
        Params::Validate:              0.64
        DateTime:                      0.1402
        DateTime::Locale:              0.35
        DateTime::TimeZone:            0.25
resources:
        licence:        http://dev.perl.org/licenses/
        homepage:       http://datetime-format-strptime.googlecode.com/
        bugtracker:     http://code.google.com/p/datetime-format-strptime/issues/list
        repository:     http://datetime-format-strptime.googlecode.com/svn/trunk/
        MailingList:    http://lists.cpan.org/showlist.cgi?name=datetime
generated_by:   Rick Measham <rickm@cpan.org>

