#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Format-Strptime
version:      1.06
version_from: lib/DateTime/Format/Strptime.pm
installdirs:  site
requires:
    DateTime:                      0.1402
    DateTime::Locale:              0.02
    DateTime::TimeZone:            0.25
    Params::Validate:              0.64

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
